### ISSUE TITLE
I see a MiXs ID column on right hand side of mixs_v5.xlsx, MixSsoil_... etc.

### ISSUE THREAD

**Issue by ddooley** [GenomicsStandardsConsortium/mixs-legacy#2]
Is this being established in an ontology somewhere?  Also are plans afoot to define ontology terms or point to them for the MixS categorical variable fields?

Thanks for info,
Damion

**Comment by ramonawalls** [comment]
@ddooley We are working to create MIxS as RDF (https://github.com/GenomicsStandardsConsortium/mixs-rdf) in which each MIxS term, checklist, and controlled vocabulary will have a URI. We are aware of those numbers and will map to them with the new RDF terms. I doubt if we will be able to reuse them directly, because many terms map to multiple IDs (one per package). If MIxS as RDF is something you would be able to use, we welcome your input either via the issue tracker or at our monthly calls.

**Comment by ddooley** [comment]
I guess any newly minted RDF MIxS ids aren't technically ontology terms, so could only be referenced via hasDbXRef?  Many of the MIxS terms are relevant to biosample collection as recorded datums, and so would map to new subclasses of OBI 'data item'.  We're interested in listing them in GenEpiO, or they would perhaps be in ENVO, if not appropriate for OBI directly.

**Comment by ramonawalls** [comment]
@ddooley The mixs as rdf group has been discussing how the mixs terms will map to ontologies. We feel that the mixs terms themselves should not be an ontology, but should be rdf properties. That said, many of us work with ontologies, and we want to ensure that there is a standard way to represent mixs terms in ontologies, rather than multiple ad hoc solutions. I expect that the terms will not fit nicely into any single existing ontology, because of their diversity (e.g., compare `sequencing machine` to `carbon`.  Work on that can come after we complete mixs as rdf, which is our highest priority now.

**Comment by ddooley** [comment]
Ok, I think this can be closed now then.  I'll expect to have our ontology terms for measurable datums to have dbxrefs to MIxS RDF URL's.
